# Generated by Django 5.0.4 on 2024-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(default='+254', max_length=20)),
                ('frequency', models.CharField(default='one-time', max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('dedication', models.TextField(blank=True)),
                ('support_option', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
    ]
